# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Data Science for Biologists
description:      'Preparing Biologists for the Data Era'
url:              https://github.com/catherinehulshof/Fall2018-biology
baseurl:          /Fall2018-biology
email:            cmhulshof@vcu.edu
feedbackurl:      https://docs.google.com/forms/d/e/1FAIpQLSfp_kBFY385BYU2UBHURoa5phIQh7zR5ZbW5i3vSwkGkw6QSA/viewform?usp=sf_link
author:
  name:           'Dr. Catherine Hulshof'
  url:            https://catherinehulshof.wordpress.com/

github:
  repo:           https://github.com/catherinehulshof/Fall2018-biology
  #               Be sure the 'Issues' feature is activated in 'Settings'

theme: jekyll-theme-slate